#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/dd670769-7be1-4d4f-a0a3-19a5e44ca41f # 
title: Customer System API
version: v1.0
mediaType: application/json

resourceTypes: 
  collection: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/collection-resource-type/1.0.0/collection-resource-type.raml
  single: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/single-resource-type/1.0.0/single-resource-type.raml
            
types:
  Address: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/address/1.0.0/address.raml
  Customer: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/customer/1.0.1/customer.raml
  Order: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/order/1.0.5/order.raml

traits:
  pageable: !include exchange_modules/com.mythical.retailer.corporateit.traits/pageable-trait/1.0.0/pageable-trait.raml
  sortable: !include exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/sortable-trait/1.0.0/sortable-trait.raml


/customer/{id}:
  description: Retrieves the profile details of a customer
  is: [pageable]
  uriParameters: 
    id: 
      description: The profile ID in Hybris, stored as the user's email address.
      type: string
  type: single
  get:
    responses: 
      200:
        body:
          type: !include examples/customer_example.json
          example: !include examples/customer_example.json

  /orderHistory:
    description: Retrieves the order history for a given profile id
    is: [pageable, sortable]
    type: collection
    get:
      responses: 
        200:
          body:
            type: Order[]      
            example: !include examples/order_history_example.json

                    