#%RAML 1.0
title: Hybris Profile System API
version: v1.0

types:
  HybrisProfile: !include DataTypes/HybrisProfile.raml
  HybrisOrder: !include DataTypes/HybrisOrder.raml

/profile/{hybrisId}:
  description: Retrieves the profile details of a customer
  uriParameters: 
    hybrisId: 
      description: The profile ID in Hybris, stored as the user's email address.
      type: string
  get:
    responses: 
      200:
        body: 
          application/json:
            type: HybrisProfile
      404:
        body:
          application/json:
            
  /orderHistory:
    description: Retrieves the order history for a given profile id
    get:
      responses: 
        200:
          body:
            application/json:
              type:   HybrisOrder[]
        404:
          body: 
            application/json:
                    