#%RAML 1.0
title: Hybris Profile System API
version: v1.0

types:
  HybrisProfile: !include DataTypes/HybrisProfile.raml
  HybrisOrder: !include DataTypes/HybrisOrder.raml

traits:
  pageable: !include Traits/pageable.raml
  sortable: !include Traits/sortable.raml

/profile/{hybrisId}:
  description: Retrieves the profile details of a customer
  is: [pageable]
  uriParameters: 
    hybrisId: 
      description: The profile ID in Hybris, stored as the user's email address.
      type: string
  get:
    responses: 
      200:
        body: 
          application/json:
            type: HybrisProfile
      404:
        body:
          application/json:
    
            
  /orderHistory:
    description: Retrieves the order history for a given profile id
    is: [pageable, sortable]
    get:
      responses: 
        200:
          body:
            application/json:
              type:   HybrisOrder[]
        404:
          body: 
            application/json:

/order/{orderId}:
  description: Retrieves the order details from Hybris by Order Id.
  uriParameters:
    orderId: 
      description: The Order Id in Hybris.
      type: string
  get:
    responses: 
      200:
        body: 
          application/json:
            type: HybrisOrder
      404:
        body: 
          application/json:

                    