#%RAML 1.0 DataType

type: object
properties: 
  hybrisId: integer
  numberOfItems: integer
  store: string
  status: string
  statusDisplay: string
  deliveryStatus: string
  customer: object
  
  deliveryAddresss: !include HybrisAddress.raml
  totalPriceWithTax: !include HybrisPriceObj.raml
  totalPrice: !include HybrisPriceObj.raml
  taxAmount: !include HybrisPriceObj.raml
  subTotal: !include HybrisPriceObj.raml