#%RAML 1.0 DataType

type: object
properties: 
    id: string
    firstName: string
    lastName: string
    prefix: string
    address: !include HybrisAddress.raml
    phone: string
    email: string
    currency: string
    language: string